FROM winnietsang/onnx-tensorflow:onnx1.7.0-tf1.15

RUN git clone https://github.com/onnx/onnx-tensorflow.git && cd onnx-tensorflow && git checkout v1.7.0-tf-1.15 && pip install -e .

#RUN pip install -e .

